/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.tinysvm;

public class Example extends BaseExample {
  private transient long swigCPtr;

  protected Example(long cPtr, boolean cMemoryOwn) {
    super(TinySVMJNI.Example_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Example obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TinySVMJNI.delete_Example(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int read(String arg0, String mode, int offset) {
    return TinySVMJNI.Example_read__SWIG_0(swigCPtr, this, arg0, mode, offset);
  }

  public int read(String arg0, String mode) {
    return TinySVMJNI.Example_read__SWIG_1(swigCPtr, this, arg0, mode);
  }

  public int read(String arg0) {
    return TinySVMJNI.Example_read__SWIG_2(swigCPtr, this, arg0);
  }

  public int write(String arg0, String mode, int offset) {
    return TinySVMJNI.Example_write__SWIG_0(swigCPtr, this, arg0, mode, offset);
  }

  public int write(String arg0, String mode) {
    return TinySVMJNI.Example_write__SWIG_1(swigCPtr, this, arg0, mode);
  }

  public int write(String arg0) {
    return TinySVMJNI.Example_write__SWIG_2(swigCPtr, this, arg0);
  }

  public int rebuildSVindex(Model m) {
    return TinySVMJNI.Example_rebuildSVindex(swigCPtr, this, Model.getCPtr(m), m);
  }

  public Example() {
    this(TinySVMJNI.new_Example(), true);
  }

  public Model learn(SWIGTYPE_p_TinySVM__Param arg0) {
    long cPtr = TinySVMJNI.Example_learn__SWIG_0(swigCPtr, this, SWIGTYPE_p_TinySVM__Param.getCPtr(arg0));
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public Model learn(String s) {
    long cPtr = TinySVMJNI.Example_learn__SWIG_1(swigCPtr, this, s);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public Model learn() {
    long cPtr = TinySVMJNI.Example_learn__SWIG_2(swigCPtr, this);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

}
