/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.tinysvm;

public class SWIGTYPE_p_TinySVM__feature_node {
  private transient long swigCPtr;

  protected SWIGTYPE_p_TinySVM__feature_node(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_TinySVM__feature_node() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_TinySVM__feature_node obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

