/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.chasen.tinysvm;

public interface TinySVMConstants {
  public final static int LINEAR = TinySVMJNI.LINEAR_get();
  public final static int POLY = TinySVMJNI.POLY_get();
  public final static int NEURAL = TinySVMJNI.NEURAL_get();
  public final static int RBF = TinySVMJNI.RBF_get();
  public final static int ANOVA = TinySVMJNI.ANOVA_get();

  public final static int DOUBLE_FEATURE = TinySVMJNI.DOUBLE_FEATURE_get();
  public final static int BINARY_FEATURE = TinySVMJNI.BINARY_FEATURE_get();

  public final static int SVM = TinySVMJNI.SVM_get();
  public final static int SVR = TinySVMJNI.SVR_get();
  public final static int ONE_CLASS = TinySVMJNI.ONE_CLASS_get();

}
