/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.6u-20010826-1259
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

import TinySVM;

public class BaseExample {
  private long _cPtr = 0;
  private boolean _cMemOwn = false;

  public BaseExample(long cPointer, boolean cMemoryOwn) {
    _cPtr = cPointer;
    _cMemOwn = cMemoryOwn;
  }

  public long getCPtr() {
    return _cPtr;
  };

  public  int add(String arg0) {
	return TinySVM.BaseExample_add(getCPtr(), arg0);
  }

  public  int set(int i, String arg1) {
	return TinySVM.BaseExample_set(getCPtr(), i, arg1);
  }

  public  String get(int i) {
	return TinySVM.BaseExample_get(getCPtr(), i);
  }

  public  int remove(int i) {
	return TinySVM.BaseExample_remove(getCPtr(), i);
  }

  public  int clear() {
	return TinySVM.BaseExample_clear(getCPtr());
  }

  public  int size() {
	return TinySVM.BaseExample_size(getCPtr());
  }

  public  int read(String arg0, String mode, int offset) {
	return TinySVM.BaseExample_read(getCPtr(), arg0, mode, offset);
  }

  public  int write(String arg0, String mode, int offset) {
	return TinySVM.BaseExample_write(getCPtr(), arg0, mode, offset);
  }

  public  int readSVindex(String arg0, String mode, int offset) {
	return TinySVM.BaseExample_readSVindex(getCPtr(), arg0, mode, offset);
  }

  public  int writeSVindex(String arg0, String mode, int offset) {
	return TinySVM.BaseExample_writeSVindex(getCPtr(), arg0, mode, offset);
  }

  protected void finalize() {
    _delete();
  };

  public void _delete() {
    if(getCPtr() != 0 && _cMemOwn) {
	TinySVM.delete_BaseExample(_cPtr);
	_cPtr = 0;
    }
  }

  public  int append(String f) {
	return TinySVM.BaseExample_append(getCPtr(), f);
  }

  public  int appendSVindex(String f) {
	return TinySVM.BaseExample_appendSVindex(getCPtr(), f);
  }

  public  int getDimension() {
	return TinySVM.BaseExample_getDimension(getCPtr());
  }

  public  int getNonzeroDimension() {
	return TinySVM.BaseExample_getNonzeroDimension(getCPtr());
  }

  public  double getY(int i) {
	return TinySVM.BaseExample_getY(getCPtr(), i);
  }

  public  String getX(int i) {
	return TinySVM.BaseExample_getX(getCPtr(), i);
  }

  public  double getAlpha(int i) {
	return TinySVM.BaseExample_getAlpha(getCPtr(), i);
  }

  public  double getGradient(int i) {
	return TinySVM.BaseExample_getGradient(getCPtr(), i);
  }

  public  double getG(int i) {
	return TinySVM.BaseExample_getG(getCPtr(), i);
  }

  protected BaseExample() {}

}
