/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.6u-20010826-1259
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

import TinySVM;

public class Example extends BaseExample {
  private long _cPtr = 0;
  private boolean _cMemOwn = false;

  public Example(long cPointer, boolean cMemoryOwn) {
    _cPtr = cPointer;
    _cMemOwn = cMemoryOwn;
  }

  public long getCPtr() {
    return _cPtr;
  };

  public  int read(String arg0, String mode, int offset) {
	return TinySVM.Example_read(getCPtr(), arg0, mode, offset);
  }

  public  int write(String arg0, String mode, int offset) {
	return TinySVM.Example_write(getCPtr(), arg0, mode, offset);
  }

  public  int rebuildSVindex(Model arg0) {
	return TinySVM.Example_rebuildSVindex(getCPtr(), arg0.getCPtr());
  }

  public  Model learn(String s) {
	return new Model(TinySVM.Example_learn(getCPtr(), s), false);
  }

  public Example() {
    if(getCPtr() == 0) {
         _cPtr = TinySVM.new_Example();
         _cMemOwn = true;
    }
  }

  protected void finalize() {
    _delete();
  };

  public void _delete() {
    if(getCPtr() != 0 && _cMemOwn) {
	TinySVM.delete_Example(_cPtr);
	_cPtr = 0;
    }
  }

}
