/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.6u-20010826-1259
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

import TinySVM;

public class Model extends BaseExample {
  private long _cPtr = 0;
  private boolean _cMemOwn = false;

  public Model(long cPointer, boolean cMemoryOwn) {
    _cPtr = cPointer;
    _cMemOwn = cMemoryOwn;
  }

  public long getCPtr() {
    return _cPtr;
  };

  public  int read(String arg0, String mode, int offset) {
	return TinySVM.Model_read(getCPtr(), arg0, mode, offset);
  }

  public  int write(String arg0, String mode, int offset) {
	return TinySVM.Model_write(getCPtr(), arg0, mode, offset);
  }

  public  int clear() {
	return TinySVM.Model_clear(getCPtr());
  }

  public  double classify(String arg0) {
	return TinySVM.Model_classify(getCPtr(), arg0);
  }

  public  double estimateMargin() {
	return TinySVM.Model_estimateMargin(getCPtr());
  }

  public  double estimateSphere() {
	return TinySVM.Model_estimateSphere(getCPtr());
  }

  public  double estimateVC() {
	return TinySVM.Model_estimateVC(getCPtr());
  }

  public  double estimateXA(double rho) {
	return TinySVM.Model_estimateXA(getCPtr(), rho);
  }

  public  int compress() {
	return TinySVM.Model_compress(getCPtr());
  }

  public  int getSVnum() {
	return TinySVM.Model_getSVnum(getCPtr());
  }

  public  int getBSVnum() {
	return TinySVM.Model_getBSVnum(getCPtr());
  }

  public  int getTrainingDataSize() {
	return TinySVM.Model_getTrainingDataSize(getCPtr());
  }

  public  double getLoss() {
	return TinySVM.Model_getLoss(getCPtr());
  }

  public Model() {
    if(getCPtr() == 0) {
         _cPtr = TinySVM.new_Model();
         _cMemOwn = true;
    }
  }

  protected void finalize() {
    _delete();
  };

  public void _delete() {
    if(getCPtr() != 0 && _cMemOwn) {
	TinySVM.delete_Model(_cPtr);
	_cPtr = 0;
    }
  }

}
