/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.6u-20010826-1259
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/* Implementation : Java */

#include <jni.h>
#include <stdlib.h>

#ifdef __cplusplus
#define JCALL(func, jenv) jenv->func(
#else
#define JCALL(func, jenv) (*jenv)->func(jenv,
#endif

#define J_CLASSNAME TinySVM
#define J_PACKAGE

#include <tinysvm.h>
#include <ctype.h>
#include <string.h>
#define BaseExample TinySVM::BaseExample
#define Example TinySVM::Example 
#define Model TinySVM::Model
#undef VALUEFUNC
#define VALUEFUNC(f) ((VALUE (*)())f)
extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1add(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        char *arg1 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        result = (int )arg0->add((char const *)arg1);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1set(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1, jstring jarg2) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        int arg1 ;
        char *arg2 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (int ) jarg1;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        result = (int )arg0->set(arg1,(char const *)arg2);
        jresult = (jint) result;
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT jstring JNICALL Java_TinySVM_BaseExample_1get(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
        jstring jresult = 0 ;
        BaseExample *arg0 ;
        int arg1 ;
        char *result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (int ) jarg1;
        result = (char *)arg0->get(arg1);
        if(result != NULL)
        jresult = (jstring)jenv->NewStringUTF(result);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1remove(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        int arg1 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (int ) jarg1;
        result = (int )arg0->remove(arg1);
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1clear(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        result = (int )arg0->clear();
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1size(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        result = (int )arg0->size();
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1read(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        char *arg1 ;
        char *arg2 = "r" ;
        int arg3 = 0 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        arg3 = (int ) jarg3;
        result = (int )arg0->read((char const *)arg1,(char const *)arg2,arg3);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1write(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        char *arg1 ;
        char *arg2 = "w" ;
        int arg3 = 0 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        arg3 = (int ) jarg3;
        result = (int )arg0->write((char const *)arg1,(char const *)arg2,arg3);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1readSVindex(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        char *arg1 ;
        char *arg2 = "r" ;
        int arg3 = 0 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        arg3 = (int ) jarg3;
        result = (int )arg0->readSVindex((char const *)arg1,(char const *)arg2,arg3);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1writeSVindex(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        char *arg1 ;
        char *arg2 = "w" ;
        int arg3 = 0 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        arg3 = (int ) jarg3;
        result = (int )arg0->writeSVindex((char const *)arg1,(char const *)arg2,arg3);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT void JNICALL Java_TinySVM_delete_1BaseExample(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        BaseExample *arg0 ;
        
        arg0 = *(BaseExample **)&jarg0;
        delete arg0;
}}


int  BaseExample_append(BaseExample *self,char *f) {
    {
        return self->write(f,"a"); 
    }
}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1append(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        char *arg1 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        result = (int )BaseExample_append(arg0,arg1);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        return jresult;
}}


int  BaseExample_appendSVindex(BaseExample *self,char *f) {
    {
        return self->writeSVindex(f,"a"); 
    }
}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1appendSVindex(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        char *arg1 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        result = (int )BaseExample_appendSVindex(arg0,arg1);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        return jresult;
}}


int  BaseExample_getDimension(BaseExample *self) {
    {
        return self->d; 
    }
}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1getDimension(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        result = (int )BaseExample_getDimension(arg0);
        jresult = (jint) result;
        return jresult;
}}


int  BaseExample_getNonzeroDimension(BaseExample *self) {
    {
        return self->pack_d; 
    }
}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_BaseExample_1getNonzeroDimension(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        BaseExample *arg0 ;
        int result ;
        
        arg0 = *(BaseExample **)&jarg0;
        result = (int )BaseExample_getNonzeroDimension(arg0);
        jresult = (jint) result;
        return jresult;
}}


double  BaseExample_getY(BaseExample *self,int i) {
    {
        if (i >= 0 && i < self->l) return self->y[i];
        fprintf(stderr, "BaseExample::getY() -- index is out of range\n");
        return 0.0;
    }
}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_BaseExample_1getY(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
        jdouble jresult = 0 ;
        BaseExample *arg0 ;
        int arg1 ;
        double result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (int ) jarg1;
        result = (double )BaseExample_getY(arg0,arg1);
        jresult = (jdouble) result;
        return jresult;
}}


char const * BaseExample_getX(BaseExample *self,int i) {
    {
        const char *s = self->get(i);
        if (!s) return 0;
        
        int len = strlen (s);
        int i;
        for (i = 0; i < len;) {
            while (isspace (s[i])) i++;
            while (i < len && !isspace (s[i])) i++;
            while (i < len && isspace (s[i]))  i++;
            break;
        }
        
        return (const char*)(s + i);
    }
}


extern "C"{
    JNIEXPORT jstring JNICALL Java_TinySVM_BaseExample_1getX(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
        jstring jresult = 0 ;
        BaseExample *arg0 ;
        int arg1 ;
        char *result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (int ) jarg1;
        result = (char *)BaseExample_getX(arg0,arg1);
        if(result != NULL)
        jresult = (jstring)jenv->NewStringUTF(result);
        return jresult;
}}


double  BaseExample_getAlpha(BaseExample *self,int i) {
    {
        if (self->alpha && i >= 0 && i < self->svindex_size) return self->alpha[i];
        fprintf(stderr, "BaseExample::getAlpha() -- \nalpha is not available or index is out of range\n");
        return 0.0;
    }
}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_BaseExample_1getAlpha(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
        jdouble jresult = 0 ;
        BaseExample *arg0 ;
        int arg1 ;
        double result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (int ) jarg1;
        result = (double )BaseExample_getAlpha(arg0,arg1);
        jresult = (jdouble) result;
        return jresult;
}}


double  BaseExample_getGradient(BaseExample *self,int i) {
    {
        if (self->G && i >= 0 && i < self->svindex_size) return self->G[i];
        fprintf(stderr, "BaseExample::getGradient() -- \ngradient is not available or index is out of range\n");
        return 0.0;
    }
}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_BaseExample_1getGradient(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
        jdouble jresult = 0 ;
        BaseExample *arg0 ;
        int arg1 ;
        double result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (int ) jarg1;
        result = (double )BaseExample_getGradient(arg0,arg1);
        jresult = (jdouble) result;
        return jresult;
}}


double  BaseExample_getG(BaseExample *self,int i) {
    {
        if (self->G && i >= 0 && i < self->svindex_size) return self->G[i];
        fprintf(stderr, "BaseExample::getG() -- index is out of range\n");
        return 0.0;
    }
}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_BaseExample_1getG(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
        jdouble jresult = 0 ;
        BaseExample *arg0 ;
        int arg1 ;
        double result ;
        
        arg0 = *(BaseExample **)&jarg0;
        arg1 = (int ) jarg1;
        result = (double )BaseExample_getG(arg0,arg1);
        jresult = (jdouble) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Model_1read(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
        jint jresult = 0 ;
        Model *arg0 ;
        char *arg1 ;
        char *arg2 = "r" ;
        int arg3 = 0 ;
        int result ;
        
        arg0 = *(Model **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        arg3 = (int ) jarg3;
        result = (int )arg0->read((char const *)arg1,(char const *)arg2,arg3);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Model_1write(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
        jint jresult = 0 ;
        Model *arg0 ;
        char *arg1 ;
        char *arg2 = "w" ;
        int arg3 = 0 ;
        int result ;
        
        arg0 = *(Model **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        arg3 = (int ) jarg3;
        result = (int )arg0->write((char const *)arg1,(char const *)arg2,arg3);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Model_1clear(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        Model *arg0 ;
        int result ;
        
        arg0 = *(Model **)&jarg0;
        result = (int )arg0->clear();
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_Model_1classify(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
        jdouble jresult = 0 ;
        Model *arg0 ;
        char *arg1 ;
        double result ;
        
        arg0 = *(Model **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        result = (double )arg0->classify((char const *)arg1);
        jresult = (jdouble) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        return jresult;
}}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_Model_1estimateMargin(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jdouble jresult = 0 ;
        Model *arg0 ;
        double result ;
        
        arg0 = *(Model **)&jarg0;
        result = (double )arg0->estimateMargin();
        jresult = (jdouble) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_Model_1estimateSphere(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jdouble jresult = 0 ;
        Model *arg0 ;
        double result ;
        
        arg0 = *(Model **)&jarg0;
        result = (double )arg0->estimateSphere();
        jresult = (jdouble) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_Model_1estimateVC(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jdouble jresult = 0 ;
        Model *arg0 ;
        double result ;
        
        arg0 = *(Model **)&jarg0;
        result = (double )arg0->estimateVC();
        jresult = (jdouble) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_Model_1estimateXA(JNIEnv *jenv, jclass jcls, jlong jarg0, jdouble jarg1) {
        jdouble jresult = 0 ;
        Model *arg0 ;
        double arg1 = 2.0 ;
        double result ;
        
        arg0 = *(Model **)&jarg0;
        arg1 = (double ) jarg1;
        result = (double )arg0->estimateXA(arg1);
        jresult = (jdouble) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Model_1compress(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        Model *arg0 ;
        int result ;
        
        arg0 = *(Model **)&jarg0;
        result = (int )arg0->compress();
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Model_1getSVnum(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        Model *arg0 ;
        int result ;
        
        arg0 = *(Model **)&jarg0;
        result = (int )arg0->getSVnum();
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Model_1getBSVnum(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        Model *arg0 ;
        int result ;
        
        arg0 = *(Model **)&jarg0;
        result = (int )arg0->getBSVnum();
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Model_1getTrainingDataSize(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jint jresult = 0 ;
        Model *arg0 ;
        int result ;
        
        arg0 = *(Model **)&jarg0;
        result = (int )arg0->getTrainingDataSize();
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jdouble JNICALL Java_TinySVM_Model_1getLoss(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        jdouble jresult = 0 ;
        Model *arg0 ;
        double result ;
        
        arg0 = *(Model **)&jarg0;
        result = (double )arg0->getLoss();
        jresult = (jdouble) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jlong JNICALL Java_TinySVM_new_1Model(JNIEnv *jenv, jclass jcls) {
        jlong jresult = 0 ;
        Model *result ;
        
        result = (Model *)new Model();
        *(Model **)&jresult = result;
        return jresult;
}}


extern "C"{
    JNIEXPORT void JNICALL Java_TinySVM_delete_1Model(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        Model *arg0 ;
        
        arg0 = *(Model **)&jarg0;
        delete arg0;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Example_1read(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
        jint jresult = 0 ;
        Example *arg0 ;
        char *arg1 ;
        char *arg2 = "r" ;
        int arg3 = 0 ;
        int result ;
        
        arg0 = *(Example **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        arg3 = (int ) jarg3;
        result = (int )arg0->read((char const *)arg1,(char const *)arg2,arg3);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Example_1write(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
        jint jresult = 0 ;
        Example *arg0 ;
        char *arg1 ;
        char *arg2 = "w" ;
        int arg3 = 0 ;
        int result ;
        
        arg0 = *(Example **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        arg2 = (jarg2) ? (char *)jenv->GetStringUTFChars(jarg2, 0) : NULL;
        arg3 = (int ) jarg3;
        result = (int )arg0->write((char const *)arg1,(char const *)arg2,arg3);
        jresult = (jint) result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        if(arg2) jenv->ReleaseStringUTFChars(jarg2, arg2);
        return jresult;
}}


extern "C"{
    JNIEXPORT jint JNICALL Java_TinySVM_Example_1rebuildSVindex(JNIEnv *jenv, jclass jcls, jlong jarg0, jlong jarg1) {
        jint jresult = 0 ;
        Example *arg0 ;
        Model *arg1 ;
        int result ;
        
        arg0 = *(Example **)&jarg0;
        arg1 = *(Model **)&jarg1;
        result = (int )arg0->rebuildSVindex(arg1);
        jresult = (jint) result;
        return jresult;
}}


extern "C"{
    JNIEXPORT jlong JNICALL Java_TinySVM_Example_1learn(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
        jlong jresult = 0 ;
        Example *arg0 ;
        char *arg1 = 0 ;
        Model *result ;
        
        arg0 = *(Example **)&jarg0;
        arg1 = (jarg1) ? (char *)jenv->GetStringUTFChars(jarg1, 0) : NULL;
        result = (Model *)arg0->learn((char const *)arg1);
        *(Model **)&jresult = result;
        if(arg1) jenv->ReleaseStringUTFChars(jarg1, arg1);
        return jresult;
}}


extern "C"{
    JNIEXPORT jlong JNICALL Java_TinySVM_new_1Example(JNIEnv *jenv, jclass jcls) {
        jlong jresult = 0 ;
        Example *result ;
        
        result = (Example *)new Example();
        *(Example **)&jresult = result;
        return jresult;
}}


extern "C"{
    JNIEXPORT void JNICALL Java_TinySVM_delete_1Example(JNIEnv *jenv, jclass jcls, jlong jarg0) {
        Example *arg0 ;
        
        arg0 = *(Example **)&jarg0;
        delete arg0;
}}



