/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.6u-20010826-1259
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct swig_type_info {
  const char  *name;                 
  void *(*converter)(void *);
  const char  *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
SWIGEXPORT(swig_type_info *) SWIG_TypeQuery(const char *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

#endif

#ifdef __cplusplus
}
#endif



/* -----------------------------------------------------------------------------
 * perl5.swg
 *
 * Perl5 runtime library
 * $Header: /cl/lab/cvsroot/taku-ku/TinySVM/perl/TinySVM_wrap.c,v 1.2 2001/08/29 14:52:46 taku-ku Exp $
 * ----------------------------------------------------------------------------- */

#define SWIGPERL
#define SWIGPERL5
#ifdef __cplusplus
/* Needed on some windows machines---since MS plays funny
   games with the header files under C++ */
#include <math.h>
#include <stdlib.h>
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

/* Get rid of free and malloc defined by perl */
#undef free
#undef malloc

#include <string.h>
#ifdef __cplusplus
}
#endif

#ifdef PERL_OBJECT
#define MAGIC_PPERL  CPerlObj *pPerl = (CPerlObj *) this;
#define MAGIC_CAST   (int (CPerlObj::*)(SV *, MAGIC *))
#define SWIGCLASS_STATIC 
#else
#define MAGIC_PPERL
#define MAGIC_CAST
#define SWIGCLASS_STATIC static
#endif

#if defined(WIN32) && defined(PERL_OBJECT) && !defined(PerlIO_exportFILE)
#define PerlIO_exportFILE(fh,fl) (FILE*)(fh)
#endif

/* Modifications for newer Perl 5.005 releases */

#if !defined(PERL_REVISION) || ((PERL_REVISION >= 5) && ((PERL_VERSION < 5) || ((PERL_VERSION == 5) && (PERL_SUBVERSION < 50))))
#ifndef PL_sv_yes
#define PL_sv_yes sv_yes
#endif
#ifndef PL_sv_undef
#define PL_sv_undef sv_undef
#endif
#ifndef PL_na
#define PL_na na
#endif
#endif

#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef SWIG_NOINCLUDE

#ifndef PERL_OBJECT
extern int SWIG_ConvertPtr(SV *, void **, swig_type_info *);
extern void SWIG_MakePtr(SV *, void *, swig_type_info *);
#else
extern int _SWIG_ConvertPtr(CPerlObj *, SV *, void **, swig_type_info *);
extern void _SWIG_MakePtr(CPerlObj *, SV *, void *, swig_type_info *);
#define SWIG_ConvertPtr(a,b,c) _SWIG_ConvertPtr(pPerl,a,b,c)
#define SWIG_MakePtr(a,b,c) _SWIG_MakePtr(pPerl,a,b,c)
#endif

#endif

/* Function for getting a pointer value */

#ifndef PERL_OBJECT
SWIGRUNTIME(int) 
SWIG_ConvertPtr(SV *sv, void **ptr, swig_type_info *_t)
#else
#define SWIG_ConvertPtr(a,b,c) _SWIG_GetConvert(pPerl,a,b,c)
SWIGRUNTIME(int)
_SWIG_ConvertPtr(CPerlObj *pPerl, SV *sv, void **ptr, swig_type_info *_t)
#endif
{
  char *_c;
  swig_type_info *tc;
  IV   tmp;

  /* If magical, apply more magic */
  if (SvGMAGICAL(sv))
    mg_get(sv);

  /* Check to see if this is an object */
  if (sv_isobject(sv)) {
    SV *tsv = (SV*) SvRV(sv);
    if ((SvTYPE(tsv) == SVt_PVHV)) {
      MAGIC *mg;
      if (SvMAGICAL(tsv)) {
	mg = mg_find(tsv,'P');
	if (mg) {
	  SV *rsv = mg->mg_obj;
	  if (sv_isobject(rsv)) {
	    tmp = SvIV((SV*)SvRV(rsv));
	  }
	}
      } else {
	return -1;
      }
    } else {
      tmp = SvIV((SV*)SvRV(sv));
    }
    if (!_t) {
      *(ptr) = (void *) tmp;
      return 0;
    }
  } else if (! SvOK(sv)) {            /* Check for undef */
    *(ptr) = (void *) 0;
    return 0;
  } else if (SvTYPE(sv) == SVt_RV) {  /* Check for NULL pointer */
    *(ptr) = (void *) 0;
    if (!SvROK(sv)) 
      return 0;
    else
      return -1;
  } else {                            /* Don't know what it is */
      *(ptr) = (void *) 0;
      return -1;
  }
  if (_t) {
    /* Now see if the types match */      
    _c = HvNAME(SvSTASH(SvRV(sv)));
    tc = SWIG_TypeCheck(_c,_t);
    if (!tc) {
      *ptr = (void *) tmp;
      return -1;
    }
    *ptr = SWIG_TypeCast(tc,(void *)tmp);
    return 0;
  }
  *ptr = (void *) tmp;
  return 0;
}
#ifndef PERL_OBJECT
SWIGRUNTIME(void) 
SWIG_MakePtr(SV *sv, void *ptr, swig_type_info *t)
#else
#define SWIG_MakePtr(a,b,c) _SWIG_MakePtr(pPerl,a,b,c)
SWIGRUNTIME(int *)
_SWIG_MakePtr(CPerlObj *pPerl, SV *sv, void *ptr, swig_type_info *t)
#endif
{
  sv_setref_pv(sv, (char *) t->name, ptr);
}

/* Magic variable code */
#ifndef PERL_OBJECT
#define swig_create_magic(s,a,b,c) _swig_create_magic(s,a,b,c)
static void _swig_create_magic(SV *sv, const char *name, int (*set)(SV *, MAGIC *), int (*get)(SV *,MAGIC *)) {
#else
#define swig_create_magic(s,a,b,c) _swig_create_magic(pPerl,s,a,b,c)
static void _swig_create_magic(CPerlObj *pPerl, SV *sv, const char *name, int (CPerlObj::*set)(SV *, MAGIC *), int (CPerlObj::*get)(SV *, MAGIC *)) {
#endif
  MAGIC *mg;
  sv_magic(sv,sv,'U',(char *) name,strlen(name));
  mg = mg_find(sv,'U');
  mg->mg_virtual = (MGVTBL *) malloc(sizeof(MGVTBL));
  mg->mg_virtual->svt_get = get;
  mg->mg_virtual->svt_set = set;
  mg->mg_virtual->svt_len = 0;
  mg->mg_virtual->svt_clear = 0;
  mg->mg_virtual->svt_free = 0;
}

#ifdef __cplusplus
}
#endif







/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_BaseExample swig_types[0] 
#define  SWIGTYPE_p_Example swig_types[1] 
#define  SWIGTYPE_p_Model swig_types[2] 
static swig_type_info *swig_types[4];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    boot_TinySVM

#define SWIG_name   "TinySVMc::boot_TinySVM"
#define SWIG_varinit "TinySVMc::var_TinySVM_init();"
#ifdef __cplusplus
extern "C"
#endif
#ifndef PERL_OBJECT
SWIGEXPORT(void) SWIG_init (CV* cv);
#else
SWIGEXPORT(void) SWIG_init (CV *cv, CPerlObj *);
#endif

#include <tinysvm.h>
#include <ctype.h>
#include <string.h>
#define BaseExample TinySVM::BaseExample
#define Example TinySVM::Example 
#define Model TinySVM::Model
#undef VALUEFUNC
#define VALUEFUNC(f) ((VALUE (*)())f)
#ifdef PERL_OBJECT
#define MAGIC_CLASS _wrap_TinySVM_var::
class _wrap_TinySVM_var : public CPerlObj {
public:
#else
#define MAGIC_CLASS
#endif
SWIGCLASS_STATIC int swig_magic_readonly(SV *sv, MAGIC *mg) {
    MAGIC_PPERL
    sv = sv; mg = mg;
    croak("Value is read-only.");
    return 0;
}


#ifdef PERL_OBJECT
};
#endif

XS(_wrap_BaseExample_add) {
    BaseExample *arg0 ;
    char *arg1 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_add(self,char const *);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_add. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    result = (int )arg0->add((char const *)arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_set) {
    BaseExample *arg0 ;
    int arg1 ;
    char *arg2 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 3) || (items > 3)) 
    croak("Usage: BaseExample_set(self,i,char const *);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_set. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    arg1 = (int )SvIV(ST(1));
    if (! SvOK((SV*) ST(2))) {
        arg2 = 0; 
    }
    else {
        arg2 = (char *) SvPV(ST(2),PL_na); 
    }
    result = (int )arg0->set(arg1,(char const *)arg2);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_get) {
    BaseExample *arg0 ;
    int arg1 ;
    int argvi = 0;
    char *result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_get(self,i);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_get. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    arg1 = (int )SvIV(ST(1));
    result = (char *)arg0->get(arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_remove) {
    BaseExample *arg0 ;
    int arg1 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_remove(self,i);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_remove. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    arg1 = (int )SvIV(ST(1));
    result = (int )arg0->remove(arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_clear) {
    BaseExample *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: BaseExample_clear(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_clear. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    result = (int )arg0->clear();
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_size) {
    BaseExample *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: BaseExample_size(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_size. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    result = (int )arg0->size();
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_read) {
    BaseExample *arg0 ;
    char *arg1 ;
    char *arg2 = "r" ;
    int arg3 = 0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 4)) 
    croak("Usage: BaseExample_read(self,char const *,mode,offset);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_read. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    if (items > 2) {
        if (! SvOK((SV*) ST(2))) {
            arg2 = 0; 
        }
        else {
            arg2 = (char *) SvPV(ST(2),PL_na); 
        }
    }
    if (items > 3) {
        arg3 = (int )SvIV(ST(3));
    }
    result = (int )arg0->read((char const *)arg1,(char const *)arg2,arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_write) {
    BaseExample *arg0 ;
    char *arg1 ;
    char *arg2 = "w" ;
    int arg3 = 0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 4)) 
    croak("Usage: BaseExample_write(self,char const *,mode,offset);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_write. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    if (items > 2) {
        if (! SvOK((SV*) ST(2))) {
            arg2 = 0; 
        }
        else {
            arg2 = (char *) SvPV(ST(2),PL_na); 
        }
    }
    if (items > 3) {
        arg3 = (int )SvIV(ST(3));
    }
    result = (int )arg0->write((char const *)arg1,(char const *)arg2,arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_readSVindex) {
    BaseExample *arg0 ;
    char *arg1 ;
    char *arg2 = "r" ;
    int arg3 = 0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 4)) 
    croak("Usage: BaseExample_readSVindex(self,char const *,mode,offset);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_readSVindex. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    if (items > 2) {
        if (! SvOK((SV*) ST(2))) {
            arg2 = 0; 
        }
        else {
            arg2 = (char *) SvPV(ST(2),PL_na); 
        }
    }
    if (items > 3) {
        arg3 = (int )SvIV(ST(3));
    }
    result = (int )arg0->readSVindex((char const *)arg1,(char const *)arg2,arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_BaseExample_writeSVindex) {
    BaseExample *arg0 ;
    char *arg1 ;
    char *arg2 = "w" ;
    int arg3 = 0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 4)) 
    croak("Usage: BaseExample_writeSVindex(self,char const *,mode,offset);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_writeSVindex. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    if (items > 2) {
        if (! SvOK((SV*) ST(2))) {
            arg2 = 0; 
        }
        else {
            arg2 = (char *) SvPV(ST(2),PL_na); 
        }
    }
    if (items > 3) {
        arg3 = (int )SvIV(ST(3));
    }
    result = (int )arg0->writeSVindex((char const *)arg1,(char const *)arg2,arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_delete_BaseExample) {
    BaseExample *arg0 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: delete_BaseExample(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of delete_BaseExample. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    delete arg0;
    XSRETURN(argvi);
}


int  BaseExample_append(BaseExample *self,char *f) {
    {
        return self->write(f,"a"); 
    }
}


XS(_wrap_BaseExample_append) {
    BaseExample *arg0 ;
    char *arg1 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_append(self,f);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_append. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    result = (int )BaseExample_append(arg0,arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


int  BaseExample_appendSVindex(BaseExample *self,char *f) {
    {
        return self->writeSVindex(f,"a"); 
    }
}


XS(_wrap_BaseExample_appendSVindex) {
    BaseExample *arg0 ;
    char *arg1 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_appendSVindex(self,f);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_appendSVindex. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    result = (int )BaseExample_appendSVindex(arg0,arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


int  BaseExample_getDimension(BaseExample *self) {
    {
        return self->d; 
    }
}


XS(_wrap_BaseExample_getDimension) {
    BaseExample *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: BaseExample_getDimension(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_getDimension. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    result = (int )BaseExample_getDimension(arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


int  BaseExample_getNonzeroDimension(BaseExample *self) {
    {
        return self->pack_d; 
    }
}


XS(_wrap_BaseExample_getNonzeroDimension) {
    BaseExample *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: BaseExample_getNonzeroDimension(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_getNonzeroDimension. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    result = (int )BaseExample_getNonzeroDimension(arg0);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


double  BaseExample_getY(BaseExample *self,int i) {
    {
        if (i >= 0 && i < self->l) return self->y[i];
        fprintf(stderr, "BaseExample::getY() -- index is out of range\n");
        return 0.0;
    }
}


XS(_wrap_BaseExample_getY) {
    BaseExample *arg0 ;
    int arg1 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_getY(self,i);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_getY. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    arg1 = (int )SvIV(ST(1));
    result = (double )BaseExample_getY(arg0,arg1);
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


char const * BaseExample_getX(BaseExample *self,int i) {
    {
        const char *s = self->get(i);
        if (!s) return 0;
        
        int len = strlen (s);
        int i;
        for (i = 0; i < len;) {
            while (isspace (s[i])) i++;
            while (i < len && !isspace (s[i])) i++;
            while (i < len && isspace (s[i]))  i++;
            break;
        }
        
        return (const char*)(s + i);
    }
}


XS(_wrap_BaseExample_getX) {
    BaseExample *arg0 ;
    int arg1 ;
    int argvi = 0;
    char *result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_getX(self,i);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_getX. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    arg1 = (int )SvIV(ST(1));
    result = (char *)BaseExample_getX(arg0,arg1);
    ST(argvi) = sv_newmortal();
    sv_setpv((SV*)ST(argvi++),(char *) result);
    XSRETURN(argvi);
}


double  BaseExample_getAlpha(BaseExample *self,int i) {
    {
        if (self->alpha && i >= 0 && i < self->svindex_size) return self->alpha[i];
        fprintf(stderr, "BaseExample::getAlpha() -- \nalpha is not available or index is out of range\n");
        return 0.0;
    }
}


XS(_wrap_BaseExample_getAlpha) {
    BaseExample *arg0 ;
    int arg1 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_getAlpha(self,i);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_getAlpha. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    arg1 = (int )SvIV(ST(1));
    result = (double )BaseExample_getAlpha(arg0,arg1);
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


double  BaseExample_getGradient(BaseExample *self,int i) {
    {
        if (self->G && i >= 0 && i < self->svindex_size) return self->G[i];
        fprintf(stderr, "BaseExample::getGradient() -- \ngradient is not available or index is out of range\n");
        return 0.0;
    }
}


XS(_wrap_BaseExample_getGradient) {
    BaseExample *arg0 ;
    int arg1 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_getGradient(self,i);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_getGradient. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    arg1 = (int )SvIV(ST(1));
    result = (double )BaseExample_getGradient(arg0,arg1);
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


double  BaseExample_getG(BaseExample *self,int i) {
    {
        if (self->G && i >= 0 && i < self->svindex_size) return self->G[i];
        fprintf(stderr, "BaseExample::getG() -- index is out of range\n");
        return 0.0;
    }
}


XS(_wrap_BaseExample_getG) {
    BaseExample *arg0 ;
    int arg1 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: BaseExample_getG(self,i);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_BaseExample) < 0) {
        croak("Type error in argument 1 of BaseExample_getG. Expected %s", SWIGTYPE_p_BaseExample->name);
        XSRETURN(1);
    }
    arg1 = (int )SvIV(ST(1));
    result = (double )BaseExample_getG(arg0,arg1);
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_read) {
    Model *arg0 ;
    char *arg1 ;
    char *arg2 = "r" ;
    int arg3 = 0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 4)) 
    croak("Usage: Model_read(self,char const *,mode,offset);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_read. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    if (items > 2) {
        if (! SvOK((SV*) ST(2))) {
            arg2 = 0; 
        }
        else {
            arg2 = (char *) SvPV(ST(2),PL_na); 
        }
    }
    if (items > 3) {
        arg3 = (int )SvIV(ST(3));
    }
    result = (int )arg0->read((char const *)arg1,(char const *)arg2,arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_write) {
    Model *arg0 ;
    char *arg1 ;
    char *arg2 = "w" ;
    int arg3 = 0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 4)) 
    croak("Usage: Model_write(self,char const *,mode,offset);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_write. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    if (items > 2) {
        if (! SvOK((SV*) ST(2))) {
            arg2 = 0; 
        }
        else {
            arg2 = (char *) SvPV(ST(2),PL_na); 
        }
    }
    if (items > 3) {
        arg3 = (int )SvIV(ST(3));
    }
    result = (int )arg0->write((char const *)arg1,(char const *)arg2,arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_clear) {
    Model *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_clear(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_clear. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (int )arg0->clear();
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_classify) {
    Model *arg0 ;
    char *arg1 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: Model_classify(self,char const *);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_classify. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    result = (double )arg0->classify((char const *)arg1);
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_estimateMargin) {
    Model *arg0 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_estimateMargin(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_estimateMargin. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (double )arg0->estimateMargin();
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_estimateSphere) {
    Model *arg0 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_estimateSphere(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_estimateSphere. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (double )arg0->estimateSphere();
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_estimateVC) {
    Model *arg0 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_estimateVC(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_estimateVC. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (double )arg0->estimateVC();
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_estimateXA) {
    Model *arg0 ;
    double arg1 = 2.0 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 1) || (items > 2)) 
    croak("Usage: Model_estimateXA(self,rho);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_estimateXA. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    if (items > 1) {
        arg1 = (double )SvNV(ST(1));
    }
    result = (double )arg0->estimateXA(arg1);
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_compress) {
    Model *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_compress(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_compress. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (int )arg0->compress();
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_getSVnum) {
    Model *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_getSVnum(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_getSVnum. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (int )arg0->getSVnum();
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_getBSVnum) {
    Model *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_getBSVnum(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_getBSVnum. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (int )arg0->getBSVnum();
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_getTrainingDataSize) {
    Model *arg0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_getTrainingDataSize(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_getTrainingDataSize. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (int )arg0->getTrainingDataSize();
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Model_getLoss) {
    Model *arg0 ;
    int argvi = 0;
    double result ;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: Model_getLoss(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of Model_getLoss. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (double )arg0->getLoss();
    ST(argvi) = sv_newmortal();
    sv_setnv(ST(argvi++), (double) result);
    XSRETURN(argvi);
}


XS(_wrap_new_Model) {
    int argvi = 0;
    Model *result ;
    dXSARGS;
    
    if ((items < 0) || (items > 0)) 
    croak("Usage: new_Model();");
    result = (Model *)new Model();
    ST(argvi) = sv_newmortal();
    SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_Model);
    XSRETURN(argvi);
}


XS(_wrap_delete_Model) {
    Model *arg0 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: delete_Model(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 1 of delete_Model. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    delete arg0;
    XSRETURN(argvi);
}


XS(_wrap_Example_read) {
    Example *arg0 ;
    char *arg1 ;
    char *arg2 = "r" ;
    int arg3 = 0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 4)) 
    croak("Usage: Example_read(self,char const *,mode,offset);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Example) < 0) {
        croak("Type error in argument 1 of Example_read. Expected %s", SWIGTYPE_p_Example->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    if (items > 2) {
        if (! SvOK((SV*) ST(2))) {
            arg2 = 0; 
        }
        else {
            arg2 = (char *) SvPV(ST(2),PL_na); 
        }
    }
    if (items > 3) {
        arg3 = (int )SvIV(ST(3));
    }
    result = (int )arg0->read((char const *)arg1,(char const *)arg2,arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Example_write) {
    Example *arg0 ;
    char *arg1 ;
    char *arg2 = "w" ;
    int arg3 = 0 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 4)) 
    croak("Usage: Example_write(self,char const *,mode,offset);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Example) < 0) {
        croak("Type error in argument 1 of Example_write. Expected %s", SWIGTYPE_p_Example->name);
        XSRETURN(1);
    }
    if (! SvOK((SV*) ST(1))) {
        arg1 = 0; 
    }
    else {
        arg1 = (char *) SvPV(ST(1),PL_na); 
    }
    if (items > 2) {
        if (! SvOK((SV*) ST(2))) {
            arg2 = 0; 
        }
        else {
            arg2 = (char *) SvPV(ST(2),PL_na); 
        }
    }
    if (items > 3) {
        arg3 = (int )SvIV(ST(3));
    }
    result = (int )arg0->write((char const *)arg1,(char const *)arg2,arg3);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Example_rebuildSVindex) {
    Example *arg0 ;
    Model *arg1 ;
    int argvi = 0;
    int result ;
    dXSARGS;
    
    if ((items < 2) || (items > 2)) 
    croak("Usage: Example_rebuildSVindex(self,Model *);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Example) < 0) {
        croak("Type error in argument 1 of Example_rebuildSVindex. Expected %s", SWIGTYPE_p_Example->name);
        XSRETURN(1);
    }
    if (SWIG_ConvertPtr(ST(1),(void **) &arg1,SWIGTYPE_p_Model) < 0) {
        croak("Type error in argument 2 of Example_rebuildSVindex. Expected %s", SWIGTYPE_p_Model->name);
        XSRETURN(1);
    }
    result = (int )arg0->rebuildSVindex(arg1);
    ST(argvi) = sv_newmortal();
    sv_setiv(ST(argvi++),(IV) result);
    XSRETURN(argvi);
}


XS(_wrap_Example_learn) {
    Example *arg0 ;
    char *arg1 = 0 ;
    int argvi = 0;
    Model *result ;
    dXSARGS;
    
    if ((items < 1) || (items > 2)) 
    croak("Usage: Example_learn(self,s);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Example) < 0) {
        croak("Type error in argument 1 of Example_learn. Expected %s", SWIGTYPE_p_Example->name);
        XSRETURN(1);
    }
    if (items > 1) {
        if (! SvOK((SV*) ST(1))) {
            arg1 = 0; 
        }
        else {
            arg1 = (char *) SvPV(ST(1),PL_na); 
        }
    }
    result = (Model *)arg0->learn((char const *)arg1);
    ST(argvi) = sv_newmortal();
    SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_Model);
    XSRETURN(argvi);
}


XS(_wrap_new_Example) {
    int argvi = 0;
    Example *result ;
    dXSARGS;
    
    if ((items < 0) || (items > 0)) 
    croak("Usage: new_Example();");
    result = (Example *)new Example();
    ST(argvi) = sv_newmortal();
    SWIG_MakePtr(ST(argvi++), (void *) result, SWIGTYPE_p_Example);
    XSRETURN(argvi);
}


XS(_wrap_delete_Example) {
    Example *arg0 ;
    int argvi = 0;
    dXSARGS;
    
    if ((items < 1) || (items > 1)) 
    croak("Usage: delete_Example(self);");
    if (SWIG_ConvertPtr(ST(0),(void **) &arg0,SWIGTYPE_p_Example) < 0) {
        croak("Type error in argument 1 of delete_Example. Expected %s", SWIGTYPE_p_Example->name);
        XSRETURN(1);
    }
    delete arg0;
    XSRETURN(argvi);
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static void *_p_ExampleTo_p_BaseExample(void *x) {
    return (void *)((BaseExample *) ((Example *) x));
}
static void *_p_ModelTo_p_BaseExample(void *x) {
    return (void *)((BaseExample *) ((Model *) x));
}
static swig_type_info _swigt__p_BaseExample[] = {{"TinySVM::BaseExample", 0, "BaseExample *"},{"TinySVM::BaseExample"},{"TinySVM::Example", _p_ExampleTo_p_BaseExample},{"TinySVM::Model", _p_ModelTo_p_BaseExample},{0}};
static swig_type_info _swigt__p_Example[] = {{"TinySVM::Example", 0, "Example *"},{"TinySVM::Example"},{0}};
static swig_type_info _swigt__p_Model[] = {{"TinySVM::Model", 0, "Model *"},{"TinySVM::Model"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_BaseExample, 
_swigt__p_Example, 
_swigt__p_Model, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

XS(_wrap_perl5_TinySVM_var_init) {
    dXSARGS;
    SV *sv;
    XSRETURN(1);
}
#ifdef __cplusplus
extern "C"
#endif
XS(SWIG_init) {
    dXSARGS;
    int i;
    char *file = (char *) __FILE__;
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    newXS((char *) "TinySVMc::var_TinySVM_init", _wrap_perl5_TinySVM_var_init, file);
    newXS((char *) "TinySVMc::BaseExample_add", _wrap_BaseExample_add, file);
    newXS((char *) "TinySVMc::BaseExample_set", _wrap_BaseExample_set, file);
    newXS((char *) "TinySVMc::BaseExample_get", _wrap_BaseExample_get, file);
    newXS((char *) "TinySVMc::BaseExample_remove", _wrap_BaseExample_remove, file);
    newXS((char *) "TinySVMc::BaseExample_clear", _wrap_BaseExample_clear, file);
    newXS((char *) "TinySVMc::BaseExample_size", _wrap_BaseExample_size, file);
    newXS((char *) "TinySVMc::BaseExample_read", _wrap_BaseExample_read, file);
    newXS((char *) "TinySVMc::BaseExample_write", _wrap_BaseExample_write, file);
    newXS((char *) "TinySVMc::BaseExample_readSVindex", _wrap_BaseExample_readSVindex, file);
    newXS((char *) "TinySVMc::BaseExample_writeSVindex", _wrap_BaseExample_writeSVindex, file);
    newXS((char *) "TinySVMc::delete_BaseExample", _wrap_delete_BaseExample, file);
    newXS((char *) "TinySVMc::BaseExample_append", _wrap_BaseExample_append, file);
    newXS((char *) "TinySVMc::BaseExample_appendSVindex", _wrap_BaseExample_appendSVindex, file);
    newXS((char *) "TinySVMc::BaseExample_getDimension", _wrap_BaseExample_getDimension, file);
    newXS((char *) "TinySVMc::BaseExample_getNonzeroDimension", _wrap_BaseExample_getNonzeroDimension, file);
    newXS((char *) "TinySVMc::BaseExample_getY", _wrap_BaseExample_getY, file);
    newXS((char *) "TinySVMc::BaseExample_getX", _wrap_BaseExample_getX, file);
    newXS((char *) "TinySVMc::BaseExample_getAlpha", _wrap_BaseExample_getAlpha, file);
    newXS((char *) "TinySVMc::BaseExample_getGradient", _wrap_BaseExample_getGradient, file);
    newXS((char *) "TinySVMc::BaseExample_getG", _wrap_BaseExample_getG, file);
    newXS((char *) "TinySVMc::Model_read", _wrap_Model_read, file);
    newXS((char *) "TinySVMc::Model_write", _wrap_Model_write, file);
    newXS((char *) "TinySVMc::Model_clear", _wrap_Model_clear, file);
    newXS((char *) "TinySVMc::Model_classify", _wrap_Model_classify, file);
    newXS((char *) "TinySVMc::Model_estimateMargin", _wrap_Model_estimateMargin, file);
    newXS((char *) "TinySVMc::Model_estimateSphere", _wrap_Model_estimateSphere, file);
    newXS((char *) "TinySVMc::Model_estimateVC", _wrap_Model_estimateVC, file);
    newXS((char *) "TinySVMc::Model_estimateXA", _wrap_Model_estimateXA, file);
    newXS((char *) "TinySVMc::Model_compress", _wrap_Model_compress, file);
    newXS((char *) "TinySVMc::Model_getSVnum", _wrap_Model_getSVnum, file);
    newXS((char *) "TinySVMc::Model_getBSVnum", _wrap_Model_getBSVnum, file);
    newXS((char *) "TinySVMc::Model_getTrainingDataSize", _wrap_Model_getTrainingDataSize, file);
    newXS((char *) "TinySVMc::Model_getLoss", _wrap_Model_getLoss, file);
    newXS((char *) "TinySVMc::new_Model", _wrap_new_Model, file);
    newXS((char *) "TinySVMc::delete_Model", _wrap_delete_Model, file);
    newXS((char *) "TinySVMc::Example_read", _wrap_Example_read, file);
    newXS((char *) "TinySVMc::Example_write", _wrap_Example_write, file);
    newXS((char *) "TinySVMc::Example_rebuildSVindex", _wrap_Example_rebuildSVindex, file);
    newXS((char *) "TinySVMc::Example_learn", _wrap_Example_learn, file);
    newXS((char *) "TinySVMc::new_Example", _wrap_new_Example, file);
    newXS((char *) "TinySVMc::delete_Example", _wrap_delete_Example, file);
    ST(0) = &PL_sv_yes;
    XSRETURN(1);
}

