name: Ruby Binding on Linux

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
    steps:
      - uses: actions/checkout@v2
      - name: install TinySVM
        run: |
          ./autogen.sh
          ./configure
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: setup ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ruby -v
      - name: build
        run: |
          ruby extconf.rb
          make
          make install
        working-directory: ruby
      - name: test
        run: |
          ruby test.rb
        working-directory: ruby
