name: Java Binding on Linux

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - '8'
          - '9'
          - '10'
          - '11'
          - '12'
          - '13'
    steps:
      - uses: actions/checkout@v2
      - name: install TinySVM
        run: |
          ./autogen.sh
          ./configure
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: java -version
      # TODO
      # - name: build
      #   run: |
      #     make
      #     make install
      #   working-directory: java
